pool:
  vmImage: 'windows-latest'
  
jobs:
- job: FirstJob
  timeoutInMinutes: 10
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - bash: echo "Hello world"  
  
- job: SecondJob
  timeoutInMinutes: 10
  pool:
    vmImage: 'macos-latest'
  steps:
  - bash: echo "Hello world"    
