#To set a variable from a script, you use the task.setvariable logging command.
#This updates the environment variables for subsequent jobs. 
#Subsequent jobs have access to the new variable with macro syntax and in tasks as environment variables


steps:
# Create a variable. Note that this does not update the environment of the current script.
- bash: |
    echo "##vso[task.setvariable variable=sauce]crushed tomatoes"
    echo "my environment variable as defined in this step $(sauce)"
    echo "my environment variable as defined in this step is $SAUCE"

# An environment variable called `SAUCE` has been added to all downstream steps    
- bash: |
    echo "my environment variable is $SAUCE"

- pwsh: |
    Write-Host "my environment variable is $env:SAUCE"    
